### ISSUE TITLE
entity.name.function should be entity.name.function.go

### ISSUE THREAD

**Issue by db47h** [atom/language-go#108]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`entity.name.function` should be `entity.name.function.go`

This is used for function names in function definitions. This bug prevent theming of these entities (still doable, but hackish).

### Steps to Reproduce

Try to theme `entity.name.function` like any other entity in a go source file:

```less
.syntax--go {
    &.syntax--entity {
        &.syntax--name {
             &.syntax--function {
                color: @green; // or whatever color different from your current theme
             }
             &.syntax--type {
                color: @yellow;
             }
        }
    }
}
```

**Expected behavior:** Function names to appear green in function definitions.

**Actual behavior:** No change in function name color.

**Reproduces how often:** Always

### Versions

language-go@0.43.0
